### ISSUE TITLE
float  and double   ?

### ISSUE THREAD

**Issue by StevenGardnerGMJ** [fpg1503/UIToast#1]
I  use  xcode 7.2  ios9  ,
it error   say  " float"  and "double"  between

**Comment by fpg1503** [comment]
I think #2 fixes it, I'm double checking it and if it does I'll merge it.

**Comment by fpg1503** [comment]
Closed on #2, I'll bump the version to 0.0.3

**Comment by fpg1503** [comment]
Fixed on v0.0.3
